# Generated by Django 5.1.3 on 2025-01-20 16:30

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UslugiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('uslugi', 'Услуги'), ('uslugi_oms', 'Услуги по ОМС'), ('uslugi_paid', 'Платные услуги')], max_length=50, unique=True, verbose_name='Страница')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок страницы')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контент')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uslugi_files/', verbose_name='Файл')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='Имя файла на сайте')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='uslugi.uslugipage', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Файл для страницы',
                'verbose_name_plural': 'Файлы для страниц',
            },
        ),
    ]
