# Generated by Django 5.1.3 on 2025-01-20 14:11

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('prevention', 'Профилактика'), ('clinical_examination', 'Диспансеризация'), ('medical_examinations', 'Профосмотры'), ('vaccination', 'Вакцинация'), ('covid19', 'Рекомендации по профилактике COVID-19'), ('health_school', 'Школа здоровья'), ('blood_system', 'Профилактика заболеваний системы крови'), ('Early_office', 'Кабинет раннего выявления заболеваний'), ('HIV', 'ВИЧ-инфекция')], max_length=50, unique=True, verbose_name='Страница')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок страницы')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контент')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='prevention_files/', verbose_name='Файл')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='Имя файла на сайте')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='prevention.page', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Файл для страницы',
                'verbose_name_plural': 'Файлы для страниц',
            },
        ),
    ]
