# Generated by Django 5.1.3 on 2024-12-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_departments', '0002_alter_department_department_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(default=1, verbose_name='Информация'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('adult', 'Взрослая'), ('children', 'Детская')], max_length=10, verbose_name='Отделение'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
