# Generated by Django 5.1.3 on 2024-12-13 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_departments', '0003_department_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'отделение', 'verbose_name_plural': 'Отделения больницы'},
        ),
    ]
