# Generated by Django 5.1.3 on 2024-12-13 09:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_departments', '0004_alter_department_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Информация'),
        ),
    ]
