# Generated by Django 5.1.3 on 2025-01-20 19:58

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital_departments', '0005_alter_department_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=255, verbose_name='Специальность')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата')),
                ('information', ckeditor.fields.RichTextField(verbose_name='Информация')),
                ('contact_info', ckeditor.fields.RichTextField(verbose_name='Контактная информация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='hospital_departments.department', verbose_name='Отделение больницы')),
            ],
            options={
                'verbose_name': 'вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
