# Generated by Django 5.1.3 on 2025-01-20 18:31

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Контент страницы')),
            ],
            options={
                'verbose_name': "Страница 'О нас'",
                'verbose_name_plural': "Страницы 'О нас'",
            },
        ),
        migrations.CreateModel(
            name='MainDoctorContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Информация главного врача',
                'verbose_name_plural': 'Информация главного врача',
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='aboutus_files/', verbose_name='Файл')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='Имя файла на сайте')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.aboutuspage', verbose_name='Страница')),
            ],
            options={
                'verbose_name': "Файл для страницы 'О нас'",
                'verbose_name_plural': "Файлы для страницы 'О нас'",
            },
        ),
    ]
