# Generated by Django 5.1.3 on 2025-01-20 18:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutuspage',
            options={'verbose_name': "Страница 'О нас'", 'verbose_name_plural': "Страница 'О нас'"},
        ),
        migrations.AlterModelOptions(
            name='maindoctorcontent',
            options={'verbose_name': 'Информация на главной странице', 'verbose_name_plural': 'Информация на главной странице'},
        ),
        migrations.AddField(
            model_name='maindoctorcontent',
            name='image',
            field=models.ImageField(default='main_doctor_images/default.jpg', upload_to='main_doctor_images/', verbose_name='Фото доктора'),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок (Не отображается)'),
        ),
        migrations.AlterField(
            model_name='maindoctorcontent',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='maindoctorcontent',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок (Не отображается'),
        ),
    ]
