# Generated by Django 5.1.3 on 2025-01-25 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_form', '0003_feedbackfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackFile',
        ),
    ]
