# Generated by Django 5.1.3 on 2024-12-08 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_doctor_department'),
        ('hospital_departments', '0002_alter_department_department_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='location',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='hospital_departments.department', verbose_name='Адрес'),
        ),
    ]
