# Generated by Django 5.1.3 on 2024-12-08 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_remove_doctor_location_alter_doctor_department'),
        ('hospital_departments', '0003_department_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='hospital_departments.department', verbose_name='Отделение'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=models.TextField(verbose_name='Информация'),
        ),
    ]
