# Generated by Django 5.1.3 on 2024-12-13 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_alter_doctor_department_alter_doctor_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'специалиста', 'verbose_name_plural': 'Специалисты'},
        ),
    ]
