# Generated by Django 5.1.3 on 2025-01-20 20:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_alter_doctor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Информация'),
        ),
    ]
